services:
  # 1. Nexus-AI Spring Boot REST API
  - type: web
    name: nexus-ai-backend
    env: docker
    dockerfilePath: ./BackEnd/Dockerfile
    dockerContext: ./BackEnd
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: OLLAMA_BASE_URL
        sync: false
