services:
  # 1. Nexus-AI Spring Boot REST API
  - type: web
    name: nexus-ai-backend
    env: docker
    dockerfilePath: ./BackEnd/Dockerfile
    dockerContext: ./BackEnd
    plan: free
    healthCheckPath: /api/projects
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
